### ISSUE TITLE
Day1 solution.

### ISSUE THREAD

**Issue by limjinsun** [DestyNova/advent_of_code_2020#1]
Why did you choose 3 elements? Whereas description says...

```
Find the two entries that sum to 2020; what do you get if you multiply them together?
```

**Comment by DestyNova** [comment]
Hi @limjinsun -- you've probably already noticed that part 2 of the problem requires solving for three numbers. This is why later on, I started saving the solutions in a Part1.hs and Part2.hs :grinning:
